### ISSUE TITLE
Is nightly build with wpa_supplicant ?

### ISSUE THREAD

**Issue by sheychen290** [AsteroidOS/meta-swift-hybris#2]
Swift works great but bluetooth isn't supported #1 .
So I tried to enable wifi but I can find ```/etc/wpa_supplicant.conf``` and ```wpa_cli```

Is swift nightly build with wifi support ?
```IMAGE_INSTALL += "android-tools android-system msm-fb-refresher brcm-patchram-plus iproute2 wpa-supplicant"```

**Comment by anyc** [comment]
In https://github.com/AsteroidOS/meta-swift-hybris/blob/master/conf/machine/swift.conf wpa-supplicant is not present. I guess, I added it manually during my tests. We can add it in this repo, though.

And for the record: the wifi interface is not available automatically. One has to execute `echo "" > /dev/wcnss_wlan` and _afterwards_ load wlan.ko

**Comment by FlorentRevest** [comment]
The reason why wpa-supplicant is not included by default is I would prefer having the wifi being entirely handled by connman.

For wcnss_wlan, you should add a recipe similar to the one used for patchram, to run this daemon at boottime in a systemd service.

**Comment by sheychen290** [comment]
Keep only one connection manager is logic.
```connmand -n``` is running but Wifi can't be configure from UI and ```connmanctl``` is not found

How or where configure wifi ```SSID``` and password  ?

**Comment by FlorentRevest** [comment]
You'll need to make your own build and add connmanctl to the list of packages to install.

**Comment by sheychen290** [comment]
Is Wifi Settings plained ? because bitbake is broken on Archlinux, So I can't build custom images.

**Comment by FlorentRevest** [comment]
You should setup a container with a sane distribution in which you can build Asteroid.

Wifi settings will not happen from my side for 1.0. If you want this feature before, you'll need to develop it.

**Comment by sheychen290** [comment]
Ok. Thanks
