### ISSUE TITLE
Alarmclock vibrate only one time

### ISSUE THREAD

**Issue by sheychen290** [AsteroidOS/meta-swift-hybris#3]
Move from [asteroid-alarmclock](https://github.com/AsteroidOS/asteroid-alarmclock/issues/6)
> On ZenWatch 3 (swift),
> Alarmclock vibrates only one short pulse.
> 
> With 8 august nightly image.

Reply:
FlorentRevest
> You/Your device's maintainer needs to convert the android's timed-output vibrator driver to a ffmemless driver. Similarly to what has been done here: https://github.com/AsteroidOS/meta-dory-hybris/blob/master/recipes-kernel/linux/linux-dory/0003-msm_pwm_vibrator-Convert-timed_output-APIs-to-ff_mem.patch and here: https://github.com/AsteroidOS/meta-bass-hybris/blob/master/recipes-kernel/linux/linux-bass/0004-msm_pwm_vibrator-Convert-timed_output-APIs-to-ff_mem.patch

**Comment by cvoges12** [comment]
@sheychen290 Do you know if this can be ported to the Zenwatch?

**Comment by sheychen290** [comment]
No idea, it's just a response from @FlorentRevest who said that the device manager should do it. Unfortunately @anyc was not available at that time.

**Comment by MagneFire** [comment]
@FlorentRevest shouldn't this be fixed with https://github.com/AsteroidOS/meta-asteroid/commit/b68092cd4f6b5ff91a6f3b7a6631493419c0c3f5 also?
