### ISSUE TITLE
Sensors not working

### ISSUE THREAD

**Issue by anyc** [AsteroidOS/meta-swift-hybris#5]
test_sensors reports:
```
Hardware module ID: sensors
Hardware module Name: MultiHal Sensor Module
Hardware module Author: Google, Inc
Hardware module API version: 0x1
Hardware HAL API version: 0x1
Poll device version: 0x1030001
API VERSION 0.1 (legacy): 0x1
API VERSION 0.1: 0x65537
API VERSION 1.0: 0x16777217
API VERSION 1.1: 0x16842753
API VERSION 1.2: 0x16908289
API VERSION 1.3: 0x16973825
API VERSION 1.4: 0x17039361
Got 0 sensors
```
sensors.qcom starts without error, sensorfwd also runs and no error in the kernel log that looks related. Hence, I'm not really sure where to investigate further.

sensors.swift.so is in /system/lib/hw/, sensors.ssc.so is in /system/vendor/lib/

**Comment by cvoges12** [comment]
@anyc I found this:
https://android.googlesource.com/platform/hardware/interfaces/+/master/sensors/1.0/default/Sensors.cpp

Is this any help?

**Comment by MagneFire** [comment]
If this is still of interest can you try to add the lines:
```sh
service sensors /system/bin/sensors.qcom
    class core
```
in /init.rc

Similar to https://github.com/AsteroidOS/meta-lenok-hybris/commit/e70cc4b1e68e445004901be7889c532188b94e81 and https://github.com/AsteroidOS/meta-bass-hybris/commit/9120510364ef072e2f616b3a98f7244357bc3d50#diff-14e44b86ee915277bbab6c31992417a0

Does this change anything?

**Comment by MagneFire** [comment]
Sorry, my previous post was stupid, as obviously you already tried that...

I am now looking into this issue too. Can you say if you had any other progress on this issue?

From what I can tell using the `logcat` is that initially `MultiHAL` doesn't want to load the libraries as (null) doesn't start with /system/vendor/lib/ or /system/lib/hw/. This is solved by starting the `sensors.qcom`.

However `sensors.qcom` appears to fail while registering a socket. There are `Unable to initialize service X with QCCI` errors. Which, if I'm not mistaken is related to the `ipc_router` or the modem.

But when I try to load the modem files from the modem partition, the kernel crashes with `A fatal modem` error.

Also, the init scripts look specifically for `/dev/msm_dsps` and `/dev/sensors`. If both exists the sensors.qcom is started. However, the path `/dev/msm_dsps` doesn't exists...

So, I guess I am also asking if you also experienced kernel crashes when loading the firmware files from the modem partition.
